### PR TITLE
Events page

### PR DESCRIPTION
**Pull request by tjrett**
Tasks completed:
* #5 
Code for events page, just a few entries in the table

### CODE REVIEW

**Comment by shinmm** [comment]
@tjrett 
I force-pushed to just change the commit message

**Review by shinmm — COMMENTED** [review]
Looks good for the initial base, we can touch up the styling later on 👍

**Review by shinmm — APPROVED** [review]

**Comment by shinmm** [comment]
@tjrett 
Might be helpful in the future to add a screenshot to the PR

Screen Shot 2020-04-14 at 4 31 25 PM

**Review by evvetter — APPROVED** [review]

**Review by guido-maldo — APPROVED** [review]
It looks pretty great. We can add more features to this page later on like allow filter/search by day and/or time range. We need to work on adding functionality to the back button and the help icon. In terms of styling, we can change the table cells background color to something white/gray for easier viewing.

**Pull request merged**
